name: MSBuild
on: push
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup NuGet.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: NuGet
      run: |
         mkdir packages
         cd packages
         nuget install boost -Version 1.70.0
         nuget install boost_serialization-vc142 -Version 1.70.0
      shell: cmd
      working-directory: src

    - name: build googletest
      run: |
        cmake .
        msbuild googletest-distribution.sln -p:Configuration=Release
      working-directory: src/googletest

    - name: build MSBuild
      run: msbuild test.sln
      shell: cmd
      working-directory: src/OpenMps/test
