name: Ubuntu-GCC CI

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: apt
      run: sudo apt install libboost-dev

    - name: build googletest
      run: |
        cmake .
        make -j4
      working-directory: src/googletest

    - name: make test
      run: make -j4
      working-directory: src/OpenMps/test

    - name: testrun
      run: ./test_OpenMps
      working-directory: src/OpenMps/test
